---
data_source: nir_spectrometer_readings
data_source_column: nir_od
title: Apparent NIR OD
mqtt_topic: nir_spectrometer_reading/nir_od
chart_key: nir_spectrometer_od
source: app
y_axis_label: AU
interpolation: stepAfter
lookback: 100000
fixed_decimals: 4
