---
data_source: nir_spectrometer_readings
data_source_column: signal_normalized
title: NIR spectrometer signal
mqtt_topic: nir_spectrometer_reading/nir_signal
chart_key: nir_spectrometer_signal
source: app
y_axis_label: AU
interpolation: stepAfter
lookback: 100000
fixed_decimals: 5
